# Generated by Django 3.1 on 2020-08-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200827_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.subcategory'),
        ),
    ]
